development:
  adapter: postgresql
  database: glamourpups_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: glamourpups_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: glamourpups_prod
  pool: 5
  timeout: 5000

